In [7]:
import sys
sys.path.append("/home/shaow/jupyter_base/pycharm_001")
base = "/home/shaow/jupyter_base/pycharm_001"

In [2]:
from bert_serving.client import BertClient

In [77]:
bs = BertClient(ip = '10.0.82.237', port=2345, check_length=False)

In [4]:
bs.status

{'identity': b'294ee760-ad77-4227-9532-fdc3b81feee2',
 'num_request': 1,
 'num_pending_request': 0,
 'pending_request': set(),
 'output_fmt': 'ndarray',
 'port': 2345,
 'port_out': 5556,
 'server_ip': '10.0.82.237',
 'client_version': '1.10.0',
 'timeout': -1}

In [5]:
bs.encode(['First do it', 'then do it right', 'then do it better'])

array([[ 0.22590284,  0.3092474 , -0.08256839, ..., -0.14456685,
        -0.47119063, -0.07071162],
       [ 0.37245125,  0.3559974 ,  0.09506309, ...,  0.09425776,
        -0.44825584, -0.17623942],
       [ 0.26777798,  0.22399873, -0.02177946, ...,  0.02863505,
        -0.37525043,  0.02919418]], dtype=float32)

In [58]:
import torch as th
import mysql_utils as mysql
db = mysql.initSQLConn()
word_f = mysql.make_all_raw_word_freq_map(2019, db)

8.0.19
10
socket 10.0.82.237:3306
979590


In [63]:
import data.pre_process.tokenizer as tok_tools
import importlib
importlib.reload(tok_tools)

<module 'data.pre_process.tokenizer' from '/home/shaow/jupyter_base/pycharm_001/data/pre_process/tokenizer.py'>

In [52]:
corpus = mysql.processApplication(2019, db)

244800


In [64]:
corpus_list = tok_tools.get_corpora_source_for_bert(corpus)

In [65]:
tokens_list = tok_tools.tokenize(corpus_list, word_tuple = word_f.items(), cut_all = False)

Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.628 seconds.
Prefix dict has been built successfully.


检测到缓存文件，清除中


In [80]:
vec_untok = bs.encode(corpus_list[0], is_tokenized=False, show_tokens=True)
vec_tok = bs.encode(tokens_list[0], is_tokenized=True, show_tokens=True)
# tokens_list[0]
# print(corpus_list[0])

In [86]:
cos = th.nn.CosineSimilarity(dim=1, eps=1e-6)
# print(output.shape, input1)
cos(th.Tensor(vec_untok[0][1]).reshape((1,-1)),
    th.Tensor(vec_untok[0][1]).reshape((1,-1)))

tensor([1.])

In [83]:
vec_tok

(array([[-0.31484097,  0.09061411, -0.47078866, ...,  0.2028908 ,
         -0.06616545, -0.35787004],
        [-0.48790976,  0.16276366, -0.46396253, ...,  0.40297738,
         -0.16321714, -0.05171515],
        [-0.18954495,  0.20123777, -0.51443446, ...,  0.66732806,
         -0.40919167, -0.31797794],
        [-0.41623116,  0.21087912, -0.45954973, ...,  0.46938366,
         -0.74338186, -0.09454936],
        [-0.5791109 ,  0.6424982 , -0.44838318, ...,  0.15205987,
          0.21739519, -0.34425628]], dtype=float32),
 [['[CLS]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '与',
   '[UNK]',
   '的',
   '[UNK]',
   '[UNK]',
   '[SEP]'],
  ['[CLS]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '和',
   '[UNK]',
   '[UNK]',
   '中',
   '[UNK]',
   '[UNK]',
   '的',
   '[UNK]',
   '给',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '[SEP]'],
  ['[CLS]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '[UNK]',
   '在',
   '的',
   '[UNK]',
   '[UNK]',

In [88]:

bs.encode(['你好'])

array([[ 2.89402127e-01, -1.35726959e-01,  7.59113804e-02,
         1.08622000e-01,  8.08755636e-01, -8.98813426e-01,
        -1.12794176e-01,  1.56334832e-01,  1.53306440e-01,
         6.95551276e-01, -3.86687696e-01,  2.84078717e-01,
         2.19945058e-01, -6.64386451e-02,  1.62503433e+00,
        -9.18402851e-01,  1.30370960e-01, -8.41506273e-02,
        -3.96908194e-01,  1.46362297e-02,  3.33878905e-01,
         3.47201645e-01, -3.00968379e-01,  8.92603248e-02,
         6.90196514e-01,  4.41093266e-01, -1.43354520e-01,
        -3.40380013e-01,  2.20468134e-01,  7.08293319e-01,
        -3.59006047e-01,  7.63582051e-01, -6.12573802e-01,
        -1.45580128e-01, -6.14848472e-02,  1.93856116e-02,
         1.42057970e-01,  1.33120567e-01,  6.90392554e-01,
         3.03425550e-01, -2.41121724e-01, -3.08391958e-01,
         2.27850676e-01,  1.25228360e-01, -9.01238993e-03,
        -4.49560374e-01,  5.61710477e-01, -4.08593535e-01,
         2.12813810e-01,  1.36784136e-01,  4.70192909e-0

In [96]:
dic = {1:'你好'}
ind = th.LongTensor(list(dic.keys()))

In [98]:
[dic[int(i)] for i in ind]

['你好']